import { describe, expect, it } from 'vitest'

import { WorkflowDefinitionGenerationService } from '../../../src/main/services/WorkflowDefinitionGenerationService'
import { getWorkflowGenerationSchemaString } from '../../../src/main/services/workflow-generation-prompt'

const buildGeneratedWorkflowResult = () => ({
  name: 'Ship feature',
  description: 'Generated by AI',
  definition: {
    version: 1,
    nodes: [
      {
        id: 'node-a',
        key: 'analyze',
        type: 'agent',
        name: 'Analyze',
        prompt: 'Inspect the request',
        command: null,
        cliToolId: null,
        agentToolConfigId: null,
        requiresApprovalAfterRun: false,
        position: { x: 0, y: 0 }
      },
      {
        id: 'node-b',
        key: 'ship',
        type: 'agent',
        name: 'Ship',
        prompt: 'Complete the work',
        command: null,
        cliToolId: null,
        agentToolConfigId: null,
        requiresApprovalAfterRun: true,
        position: { x: 320, y: 0 }
      }
    ],
    edges: [{ from: 'node-a', to: 'node-b' }]
  }
})

describe('WorkflowDefinitionGenerationService', () => {
  it('generates linear agent steps when the prompt contains multiple bullet points', async () => {
    const service = new WorkflowDefinitionGenerationService()

    const result = await service.generateDefinition({
      name: 'Ship feature',
      mode: 'rules',
      prompt: `
        1. Analyze the current implementation
        2. Implement the feature
        3. Verify the result
      `
    })

    expect(result.name).toBe('Ship feature')
    expect(result.definition.nodes).toHaveLength(3)
    expect(result.definition.nodes[0]).toEqual(
      expect.objectContaining({
        name: 'Analyze the current implementation',
        type: 'agent'
      })
    )
    expect(result.definition.nodes[2]).toEqual(
      expect.objectContaining({
        name: 'Verify the result',
        requiresApprovalAfterRun: true
      })
    )
  })

  it('detects command nodes from command-like prompts', async () => {
    const service = new WorkflowDefinitionGenerationService()

    const result = await service.generateDefinition({
      mode: 'rules',
      prompt: 'Analyze the repo then run `npm test` then summarize the failures'
    })

    expect(result.definition.nodes).toHaveLength(3)
    expect(result.definition.nodes[1]).toEqual(
      expect.objectContaining({
        type: 'command',
        command: 'npm test'
      })
    )
  })

  it('falls back to the next AI CLI when the preferred tool fails', async () => {
    const service = new WorkflowDefinitionGenerationService()
    const calls: string[] = []

    service.setCliRuntime(
      {
        runOneShotSession: async ({ toolId }: { toolId: string }) => {
          calls.push(toolId)

          if (toolId === 'claude-code') {
            throw new Error('WORKFLOW_AI_GENERATION_FAILED')
          }

          return {
            sessionId: 'session-1',
            toolId,
            code: 0,
            status: 'completed',
            stdout: JSON.stringify(buildGeneratedWorkflowResult()),
            stderr: '',
            logs: []
          }
        }
      } as never,
      {
        detectTool: async (toolId: string) => ({
          id: toolId,
          installed: true,
          configState: 'unknown'
        })
      } as never,
      {
        validateDefinitionDocument: () => undefined
      } as never
    )

    const result = await service.generateDefinition({
      name: 'Ship feature',
      prompt: 'Analyze then implement then verify',
      mode: 'ai'
    })

    expect(calls).toEqual(['claude-code', 'codex'])
    expect(result.name).toBe('Ship feature')
    expect(result.definition.edges).toEqual([{ from: 'node-a', to: 'node-b' }])
  })

  it('uses the explicitly selected AI CLI tool when provided', async () => {
    const service = new WorkflowDefinitionGenerationService()
    const calls: string[] = []

    service.setCliRuntime(
      {
        runOneShotSession: async ({ toolId }: { toolId: string }) => {
          calls.push(toolId)

          return {
            sessionId: 'session-1',
            toolId,
            code: 0,
            status: 'completed',
            stdout: JSON.stringify(buildGeneratedWorkflowResult()),
            stderr: '',
            logs: []
          }
        }
      } as never,
      {
        detectTool: async (toolId: string) => ({
          id: toolId,
          installed: true,
          configState: 'unknown'
        })
      } as never,
      {
        validateDefinitionDocument: () => undefined
      } as never
    )

    await service.generateDefinition({
      name: 'Ship feature',
      prompt: 'Analyze then implement then verify',
      mode: 'ai',
      toolId: 'codex'
    })

    expect(calls).toEqual(['codex'])
  })

  it('parses Codex JSONL item.completed agent messages', async () => {
    const service = new WorkflowDefinitionGenerationService()

    service.setCliRuntime(
      {
        runOneShotSession: async ({ toolId }: { toolId: string }) => ({
          sessionId: 'session-1',
          toolId,
          code: 0,
          status: 'completed',
          stdout: [
            JSON.stringify({ type: 'thread.started', thread_id: 'thread-1' }),
            JSON.stringify({
              type: 'item.completed',
              item: {
                id: 'item-1',
                type: 'agent_message',
                text: JSON.stringify(buildGeneratedWorkflowResult())
              }
            }),
            JSON.stringify({ type: 'turn.completed' })
          ].join('\n'),
          stderr: '',
          logs: []
        })
      } as never,
      {
        detectTool: async (toolId: string) => ({
          id: toolId,
          installed: true,
          configState: 'unknown'
        })
      } as never,
      {
        validateDefinitionDocument: () => undefined
      } as never
    )

    const result = await service.generateDefinition({
      name: 'Ship feature',
      prompt: 'Analyze then implement then verify',
      mode: 'ai',
      toolId: 'codex'
    })

    expect(result.name).toBe('Ship feature')
    expect(result.definition.edges).toEqual([{ from: 'node-a', to: 'node-b' }])
  })

  it('treats Codex turn failures as generation failures instead of parse failures', async () => {
    const service = new WorkflowDefinitionGenerationService()

    service.setCliRuntime(
      {
        runOneShotSession: async ({ toolId }: { toolId: string }) => ({
          sessionId: 'session-1',
          toolId,
          code: 1,
          status: 'error',
          stdout: [
            JSON.stringify({
              type: 'error',
              message: 'Invalid schema for response_format codex_output_schema'
            }),
            JSON.stringify({
              type: 'turn.failed',
              error: {
                message: 'Invalid schema for response_format codex_output_schema'
              }
            })
          ].join('\n'),
          stderr: '',
          logs: []
        })
      } as never,
      {
        detectTool: async (toolId: string) => ({
          id: toolId,
          installed: true,
          configState: 'unknown'
        })
      } as never,
      {
        validateDefinitionDocument: () => undefined
      } as never
    )

    await expect(
      service.generateDefinition({
        name: 'Ship feature',
        prompt: 'Analyze then implement then verify',
        mode: 'ai',
        toolId: 'codex'
      })
    ).rejects.toThrow('WORKFLOW_AI_GENERATION_FAILED')
  })
})

describe('workflow-generation-prompt schema', () => {
  it('marks all workflow node properties as required for Codex-compatible output schemas', () => {
    const schema = JSON.parse(getWorkflowGenerationSchemaString()) as {
      properties: {
        definition: {
          properties: {
            nodes: {
              items: {
                required: string[]
              }
            }
          }
        }
      }
    }

    expect(schema.properties.definition.properties.nodes.items.required).toEqual([
      'id',
      'key',
      'type',
      'name',
      'prompt',
      'command',
      'cliToolId',
      'agentToolConfigId',
      'requiresApprovalAfterRun',
      'position'
    ])
  })
})
