export const gitChannels = {
  git: {
    checkInstalled: 'git:checkInstalled',
    init: 'git:init',
    listWorktrees: 'git:listWorktrees',
    addWorktree: 'git:addWorktree',
    removeWorktree: 'git:removeWorktree',
    pruneWorktrees: 'git:pruneWorktrees',
    getDiff: 'git:getDiff',
    getStagedDiff: 'git:getStagedDiff',
    getBranches: 'git:getBranches',
    getCurrentBranch: 'git:getCurrentBranch',
    getChangedFiles: 'git:getChangedFiles',
    getBranchDiffFiles: 'git:getBranchDiffFiles',
    getBranchDiff: 'git:getBranchDiff',
    stageFiles: 'git:stageFiles',
    unstageFiles: 'git:unstageFiles',
    commit: 'git:commit',
    mergeBranch: 'git:mergeBranch',
    getConflictFiles: 'git:getConflictFiles',
    abortMerge: 'git:abortMerge',
    getConflictContent: 'git:getConflictContent',
    resolveConflict: 'git:resolveConflict',
    rebaseBranch: 'git:rebaseBranch',
    rebaseContinue: 'git:rebaseContinue',
    rebaseAbort: 'git:rebaseAbort',
    rebaseSkip: 'git:rebaseSkip',
    getRemoteUrl: 'git:getRemoteUrl',
    pushBranch: 'git:pushBranch',
    getCommitLog: 'git:getCommitLog',
    getParsedDiff: 'git:getParsedDiff',
    getParsedStagedDiff: 'git:getParsedStagedDiff',
    checkoutBranch: 'git:checkoutBranch',
    createBranch: 'git:createBranch'
  }
} as const
